{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus-stack
  name: jetson-exporter-monitor
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      path: "/metrics"
      port: metrics
      scheme: http
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: nodename
  jobLabel: jetson-exporter
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      component: metrics
      app: jetson-exporter
{{- end }}
